run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - gocyclo
    - godot
    - revive

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  godot:
    scope: toplevel
  revive:
    confidence: 0.8
  goimports:
    local-prefixes: github.com/uudon/API-Service-Hub

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
